// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PlayerDAO is an autogenerated mock type for the PlayerDAO type
type PlayerDAO struct {
	mock.Mock
}
