// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ScoreBoardDAO is an autogenerated mock type for the ScoreBoardDAO type
type ScoreBoardDAO struct {
	mock.Mock
}
