// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ScoreDAO is an autogenerated mock type for the ScoreDAO type
type ScoreDAO struct {
	mock.Mock
}

// StartConsumingScoreFromAmqp provides a mock function with given fields:
func (_m *ScoreDAO) StartConsumingScoreFromAmqp() {
	_m.Called()
}
