// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	serviceerrors "scoreBoard/internal/errors"

	mock "github.com/stretchr/testify/mock"
)

// Amqp is an autogenerated mock type for the Amqp type
type Amqp struct {
	mock.Mock
}

// ConsumeMessage provides a mock function with given fields: result
func (_m *Amqp) ConsumeMessage(result chan []byte) {
	_m.Called(result)
}

// PublishMessage provides a mock function with given fields: payload
func (_m *Amqp) PublishMessage(payload []byte) *serviceerrors.Errors {
	ret := _m.Called(payload)

	var r0 *serviceerrors.Errors
	if rf, ok := ret.Get(0).(func([]byte) *serviceerrors.Errors); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerrors.Errors)
		}
	}

	return r0
}

// createQueue provides a mock function with given fields:
func (_m *Amqp) createQueue() (string, *serviceerrors.Errors) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 *serviceerrors.Errors
	if rf, ok := ret.Get(1).(func() *serviceerrors.Errors); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerrors.Errors)
		}
	}

	return r0, r1
}
